### ISSUE TITLE
Ctrl-C Problem

### ISSUE THREAD

**Issue by mr-j0nes** [MatthewCox/colour-valgrind#4]
Hello there,

Nice piece of code. I just found one issue though. 

When sending Ctrl-C to valgrind, this will pass on the signal to the program being analyzed. If this program is handling signals it will not stop immediately and valgrind will wait for it, 'til it does the clean-up.

It seems colour-valgrind cannot handle this and when sent Ctrl-C it terminates immediately, showing following:

```
Traceback (most recent call last):
  File "/usr/local/bin/colour-valgrind", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/colourvalgrind/command_line.py", line 24, in main
    for line in iter(s.stdout.readline, b''):

```
valgrind keeps running in the background but its output is not shown anywhere..

Cheers..

**Comment by StarlitGhost** [comment]
very late response I know, but this should be fixed now thanks to https://github.com/StarlitGhost/colour-valgrind/pull/7
